debug: true
logging:
  level:
    root: debug
    tech:
      wetech:
        admin:
          mapper: trace
server:
  port: 8080
  servlet:
    context-path: /wetech-admin
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: postgres
    url: jdbc:postgresql://192.168.238.129:5432/postgres
    username: postgres
  thymeleaf:
    cache: false